GET http://localhost:4000/  

###

POST http://localhost:4000/auth/signup
Content-Type: application/json

{
  "email": "sujuka@test.com",
  "password": "333333"
}

###

POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "sujuka@test.com",
  "password": "333333"
}

###

GET http://localhost:4000/posts/private
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN1anVrYUB0ZXN0LmNvbSIsImlhdCI6MTY0ODI5NzEzMywiZXhwIjoxNjQ4NjU3MTMzfQ.s0XdTZ5ld1-FFUv71RC6PvfpnBSrFEfcfEQot0oZRzE

###


GET http://localhost:4000/posts/public
